version: "3.9"

services:
  tsu-nginx:
    image: 'nginx:stable-alpine'
    container_name: tsu-nginx
    ports:
      - '8001:80'
    volumes:
      - ./:/var/www/html
      - ./docker-configs/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  tsu-mysql:
    image: mysql:8.0.24
    user: "${UID}:${GID}"
    container_name: tsu-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
      - ./docker-configs/mysql:/var/lib/mysql/
  phpmyadmin:
    depends_on:
      - tsu-mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8002:80
    environment:
      PMA_HOST: tsu-mysql
      MYSQL_ROOT_PASSWORD: root
  tsu-app:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        UID: ${UID}
        GID: ${GID}
    container_name: tsu-app
    volumes:
      - ./:/var/www/html
